apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  generateName: kc-cicd-frontend-
  labels:
    app: kc-cicd-frontend
  selfLink: /api/v1/namespaces/cicd-development/services/kc-cicd-frontend-hlbxm
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31692
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kc-cicd-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
